## Harness GitOps Agent - Overrides File
## For default overrides, please refer to https://github.com/harness/gitops-helm/blob/main/values.yaml
## Argo CD overrides can be found at https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml

# <---Argo CD image details--->
global:
  image:
    repository: docker.io/harness/argocd
    tag: v3.3.0

# <---Harness configuration overrides--->
harness:
  identity:
    accountIdentifier: m6gpME2lTaehTN7w4-ut2A
    orgIdentifier: default
    projectIdentifier: Nextvest
    agentIdentifier: harnessagent

  secrets:
    agentSecret: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFdmdJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLZ3dnZ1NrQWdFQUFvSUJBUUM2Q2hnb0g5azNFaDRVCndTN3M1bnFPNXB3ZXNLb3JaZFR4Ly9kSGhsb0RwQzhUUHFHbERTbzNhTXRiL2dWWkFQVjZXNTJRcXlMQjd1bXcKOUZnb2JGdGl3cVRyQlE5QTJmMk1ZNkxSNWUyU0xNVm81L2xVQXpUM1hNZmVDeVcwK0FBbHdwSXBpWVJ5WVlGcgoyTkVVMTZpSVFUYXdqZXRMRkZMMTVEL0NoMUlFMy9zWlJBRmRNSFk0blVBWXMyTWxLeno4UXU0Uk5hRTdxNVY0CkZIclMvaWthSnVuUlpsN3V1T2lFcXpON3pxaEtQSk54T29Hb3NRWDhBZ291NS9pTUFsTHY4dlZYajdqdFk4a0oKVUVRSSsrV3NIMll5TmQyUzU5ZlVDM3VieWQzZlYrVVh0MTdzUG5veEdYdlltZHRVajZ4NlI2bUl6OWl2L3lEeApJYW5nWWwzVEFnTUJBQUVDZ2dFQUZjTHNoSFVGUVkzYSt1NkdBS3dORmY0ZnNPOVZXSEkyOEgvU2V3bGFLaWJnCllzM210cG5Ob0dHZnVBa0VzeDZMbUY1ekZlTU8wOFNRaldSbms0THBSYW9qQkdLNUlBcmZ2N1kvNjNHTDBwZHUKR0JGYWR0dFJMTVlya3V1VzQ0NUc1aVBXV1FsKzlxbzFLMXBYU3FyWFNlam03c3dMQStOQ3VRU1QrTHMvZXRaTgpQRHQ3V3FCOVhvSi9FdGtnMDdBSkUwVVh5cjFwN3c2ZERrN3cxNzhZb2dvZytqQU9Ha0NONFIvOFIwaTlLaG9oCmFKbytxMkRnQmhvUHM2RmFWWXhBYjUvUURia2ZoMTdEdVZUT29saE4yaEZWUng5ZFlyVVJyaFBxR25PWWhKY1EKSkJvdjc2RWw0ZVlsWW5rMmgzeTQzK1VjWElFcmxhRVM0UE1XLzI1VEVRS0JnUURqLzQ3Z085NnlQYXBFWko0QQpQREhvYkVBZVRTckxjamQ4dXJlci9aSjhvZkV6aGtxazJWY29KNitNVE5lWFd0MjIzWWprV3JIWFR0bkp3TmxJClRTT1h5UkllTWhKUHQvbngzVzZSTnVRR0JaZ2tiOGZSbFc1aU1MVGlFVU5qWmxjV3pKZzU3THNvK2wvSjRjNHMKbnBBdEZTOGI3TEhIeWQ1N2Q1aHhKWkI2RHdLQmdRRFE0MUZjZ0YxUjhHYXN0dkxlRzRFRTF5S1JRZVh5QmMvYwpNdGZ0WmxwL0ZSSURXMDJzeUVrOFZVNk9zazNQTCtsbHEwZ2M4eTRGWGxnVUtOUlJDc0ZwVnhkWnU3bDZqcUlLCk1jN2RodHV3MGNTR0VaNlZ4YkRoaDZKM0lnTHdqR0xDa1FuRlhQc0V0TUVRMllXNHRLL3d4L0Y1TDNma3VaL2MKZ2ZQUlV1dHovUUtCZ0RjZm9ZYWJVd05iSDJCN3h5dWRZaCtrbEhmL0JqcTcrYWhoYUdqZjNOdmZOM2JTb0JkdApLTUpmbmZUWTIwTVB5QTBmVUtxTk52UXNiMEYxSzlOc093L0dvR2ZHaVdEV3hVcHgwL3F0LzhGbzl0alFZY3BOClM2dlh4TlBuZ3BoMHROZWhUYWlya0xDZW9Dd3FPUFBXdmxyNEJUVEdMRkYyZ0NEdjBGNkN5NFNIQW9HQkFJd3MKNzIxZXFzRVF6U1g4QTFEdkxnNWNmRkx6NE9ZZjVsUURQb21PRlE2UXlpeThlWXlJUHpVZ25mMytRMTdVN1JBUAo5KzJOZHdXZFFRZ09PaVJFVG5SdFFEczBVWXlmNkxka28waGZkay9iQk1GZlU0ZDRTWEdlL25ScHU0VkhBQU5ICkowSnRXZm5YZm5QYk5QUTFOSmdrNUxPSkdqREFMRG5pYndhNldVelZBb0dCQUlsSDVpZUtWdVlvZGwwVzUrLzQKM3lTWWhHWkdCQzltMDdDN0c4Q0djSG1zTU95NEVXUEpjQkkyM2tXOHZjTVFqWDNrVUVoQUVHSFk0RDhKNzlWbgovY2tvTmQ3clRiTlc2MEdNeXVvK3loSC9LQ3FIMlVPaTdqc0RIRGpJMG1lY0tPNDhPTktPenMyZUtPWGM2bVNICld2VjJwSWhqcUhNUXhmaW5qNzlhZkRuZAotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
    # <---CA data overrides--->
    caData:
      enabled: false
      secret: 
    redisPassword: yzcZxDc7FVk2EA==

  gitopsServerHost: https://app.harness.io/prod1/gitops
  networkPolicy:
    create: true
  createClusterRoles: false

  configMap:
    logLevel: DEBUG

    # <---Agent communication protocol details--->
    http:
      agentHttpTarget: https://app.harness.io/gitops
      tlsEnabled: false
      certPath: /tmp/ca.bundle

    reconcile:
      appsetReconcile: true

  # <---Disaster Recovery override values--->
  disasterRecovery:
    enabled: false
    identifier: 

  # <---Openshift override values--->
  openshift:
    enabled: true
  flux:
    enabled: false
  argocdHarnessPlugin:
    enabled: false

argo-cd:
  enabled: true

# <---Argo CD configuration overrides--->

  ## IMPORTANT: Mark crds as false for Helm installations if they are already installed in the cluster
  crds:
    install: true
    keep: true

  configs:
    cm:
      cluster.inClusterEnabled: false

  # <---Redis image details--->
  redis:
    enabled: false
    image:
      repository: docker.io/harness/redis
      tag: 7.4.8-jammy

  redisSecretInit:
    enabled: true

  # <---High Availability Agent (HA) values--->
  redis-ha:
    enabled: true
    image:
      repository: docker.io/harness/redis
      tag: 7.4.8-jammy
    haproxy:
      enabled: true
      image:
        repository: docker.io/harness/haproxy
        tag: 3.2.14-alpine3.23
    configmapTest:
      ## Image for redis-ha-configmap-test hook
      image:
        repository: docker.io/harness/shellcheck
        tag: v0.5.0

  repoServer:
    replicas:  2 
    env:
      - name: HELM_PLUGINS
        value: /helm-sops-tools/helm-plugins/
      - name: HELM_SECRETS_CURL_PATH
        value: /helm-sops-tools/curl
      - name: HELM_SECRETS_SOPS_PATH
        value: /helm-sops-tools/sops
      - name: HELM_SECRETS_KUBECTL_PATH
        value: /helm-sops-tools/kubectl
      - name: HELM_SECRETS_BACKEND
        value: sops
      - name: HELM_SECRETS_VALUES_ALLOW_SYMLINKS
        value: "false"
      - name: HELM_SECRETS_VALUES_ALLOW_ABSOLUTE_PATH
        value: "true"
      - name: HELM_SECRETS_VALUES_ALLOW_PATH_TRAVERSAL
        value: "false"
      - name: HELM_SECRETS_WRAPPER_ENABLED
        value: "true"
      - name: HELM_SECRETS_HELM_PATH
        value: /usr/local/bin/helm
      - name: PATH
        value: /helm-sops-tools/helm-secrets:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    

    # <---SOPS override values--->
    initContainers:
      - name: sops-helm-secrets-tool
        image: docker.io/harness/gitops-agent-installer-helper:v0.0.13
        imagePullPolicy: IfNotPresent
        command: [ sh, -ec ]
        args:
          - |
            cp -r /custom-tools/. /helm-sops-tools
            cp /helm-sops-tools/helm-plugins/helm-secrets/scripts/wrapper/helm.sh /helm-sops-tools/helm
            mkdir -p /helm-sops-tools/helm-secrets && cp /helm-sops-tools/helm-plugins/helm-secrets/scripts/wrapper/helm.sh /helm-sops-tools/helm-secrets/helm
            chmod +x /helm-sops-tools/helm-secrets/*
            chmod +x /helm-sops-tools/*
        volumeMounts:
          - mountPath: /helm-sops-tools
            name: helm-sops-tools
    extraContainers:
      - command: [ /var/run/argocd/argocd-cmp-server ]
        image: docker.io/harness/gitops-agent-installer-helper:v0.0.13
        imagePullPolicy: IfNotPresent
        name: argocd-harness-plugin
        securityContext:
          capabilities:
            drop:
              - NET_RAW
          runAsGroup: 999
          runAsUser: 999
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          - mountPath: /tmp
            name: tmp
          - mountPath: /home/argocd/cmp-server/config/plugin.yaml
            name: argocd-harness-plugin
            subPath: harness.yaml

# <---Agent overrides--->
agent:
  harnessName: harness-agent
  image:
    repository: docker.io/harness/gitops-agent
    tag: v0.114.2

  replicas: 2

  fipsEnabled: false

  autoscaling:
    enabled: true

  highAvailability: true
  # <---Agent Proxy Config overrides--->
  proxy:
    enabled: false
    httpProxy: 
    httpsProxy: 

# <---Agent upgrader overrides--->
upgrader:
  enabled: true
  image: docker.io/harness/upgrader:latest

  config:
    # -- Proxy configuration for upgrader
    # HTTPS_PROXY=proxyScheme://proxyUser:proxyPassword@proxyHost:proxyPort
    proxyHost: 
    proxyPort: 
    proxyScheme: 
    noProxy: 
    proxyUser: 
    proxyPassword: 